### ISSUE TITLE
Theme string not right 

### ISSUE THREAD

**Issue by TPausL** [ProjektKursInfo/DevLightsApp#23]
https://drive.google.com/file/d/1P7M1nM9BU8LQ334FM5NPjmijHV3H7QFQ/view?usp=drivesdk

**Comment by Jozys** [comment]
Ist bekannt, hatte nur kein Issue dafür erstellt.
Werde das sobald wie möglich beheben

**Comment by TPausL** [comment]
jo alles gut ist mir nur so aufgefallen
