### ISSUE TITLE
picker not showing correct pattern for non existend entries

### ISSUE THREAD

**Issue by TPausL** [ProjektKursInfo/DevLightsApp#34]

**Comment by Jozys** [comment]
Bei welchem Pattern passiert es denn?

**Comment by TPausL** [comment]
runner

Es ist in der liste als aktiv wird aber entweder Single color oder was leeres angezeigt

Eigentlich ist das auch egal Weiß aber nicht wie das bei waking aussieht ob das das gleiche ist deswegen habe ich das aufgemacht

**Comment by Jozys** [comment]
Okay, ich denke mal dass das daran liegt, dass runner nicht in den Pattern steht.

Einfach weil, der DropDownPicker nach allen Pattern geht, die in den Types drin sind, und Runner da nicht drin steht.

Werde mir das später mal anschauen

**Comment by TPausL** [comment]
👍🏻Sollte auf dauer ja auch mit rein
