### ISSUE TITLE
default timeout 1 for runner

### ISSUE THREAD

**Issue by TPausL** [ProjektKursInfo/DevLightsApp#37]
1 ist villeicht nen bisschen wenig

evtl könnte man auch nen slider machen

**Comment by TPausL** [comment]
Epilepsie Warnung einbauen ist auch ne möglichkeit

**Comment by Jozys** [comment]
Okay Slider könnte man überlegen, was wäre denn nen guter Default Value?

Epilepsie Warnung ist tatsächlich sinnvoll

**Comment by TPausL** [comment]
keine ahnung 100 oder so vielleicht probiers einfach mal aus
