### ISSUE TITLE
load tags on app start

### ISSUE THREAD

**Issue by TPausL** [ProjektKursInfo/DevLightsApp#49]

**Comment by Jozys** [comment]
Habe das in 2031b1160f87857e77f5af86979d2ea2105b2988 versucht, habe versucht es zu testen, es **schien** zu funktionieren, aber es muss noch mal getestet werden im Release Build

**Comment by Jozys** [comment]
because react-redux store was removed from this app, this can be closed as with own data management the tags are loaded on app start
