### ISSUE TITLE
Empty screen when no lights in network 

### ISSUE THREAD

**Issue by TPausL** [ProjektKursInfo/DevLightsApp#60]
![Screenshot_20210524_143304_com.devlights.jpg](https://user-images.githubusercontent.com/51624718/119348367-0eda3180-bc9d-11eb-8e79-d1781a221a5c.jpg)

**Comment by Jozys** [comment]
Well. Wird gefixt...

**Comment by TPausL** [comment]
Hab aber auch nicht die aktuellste Version, weiß nicht wann du das letzte mal daran was gemacht hast

**Comment by Jozys** [comment]
Ist schon länger her, dass ich daran was verändert habe. Schaue mir das trotzdem mal an.
